DEV-346 Gitlab API definition
drud/ddev-apis pull request #30
Opened 2021-01-08 16:41 UTC by josefkarasek

## Issue ID(s):
https://ddevhq.atlassian.net/browse/DEV-346

## Tests:

## Release/Deployment notes:

2021-01-11 14:30 UTC, wozniakjan approved these changes
lgtm

2021-01-11 15:43 UTC, drekle requested changes
Short of the message structure proposed we should add these provider specific procedures deprecated and add a singular `ListGitRepositories` which provide both types so that clients do not have to merge multiple types into a common type.

2021-01-11 15:43 UTC, drekle commented on live/administration/v1alpha1/gitlabintegration.proto
> +    repeated GitlabIntegrationResponse items = 1;
Should be more descriptive than `items` here.  Response messages may contain multiple arrays.

2021-01-11 15:43 UTC, drekle commented on live/administration/v1alpha1/gitlabintegration.proto
> +    GitlabIntegrationRequest integration = 1;
we should not nest requests inside of requests.  If we wanted to do this we would simply change the delete procedure to take GitlabIntegrationRequest as its parameter instead, however I would recommend changing this to take the parameters and duplicate `GitlabIntegrationRequest` members here, however I only think you need `ID`.

2021-01-11 15:43 UTC, drekle commented on live/administration/v1alpha1/service.proto
> +    rpc CreateGitlabIntegration(CreateGitlabIntegrationRequest) returns (CreateGitlabIntegrationResponse) {
We might want to change this and deprecate the old, for ease of use from clients.

The current model:
```
GithubIntegration{
}
GitlabIntegration{
}
```

To:
```
Enum GitProvider{
  Github = 0;
  Gitlab = 1;
}
GitIntegration{
  type GitProvider
}
```
So that the call from the UI or the CLI does not have to merge these two calls, `ListGithubRepositories` and `ListGitlabRepositories` and all the heavy lifting is done server side.

2021-01-11 15:43 UTC, drekle commented on live/administration/v1alpha1/service.proto
> +    rpc CreateGitlabIntegration(CreateGitlabIntegrationRequest) returns (CreateGitlabIntegrationResponse) {
@alkymst @jdarrohn any thoughts here as well?

2021-01-11 15:43 UTC, drekle commented on live/administration/v1alpha1/gitlabintegration.proto
> +    GitlabIntegrationRequest integration = 1;
I think request objects should be 1 depth generally.

2021-01-11 15:43 UTC, drekle commented on live/administration/v1alpha1/gitlabintegration.proto
> +    GitlabIntegrationRequest integration = 1;
```
client.CreateGitlabIntegration( &CreateGitlabIntegrationRequest{
  Integration: &GitlabIntegrationRequest{
    ID: "",
    Host: "",
    Username: "",
    Token: "",
  },
})
```
just duplicate these fields where appropriate:
```
client.CreateGitlabIntegration( &CreateGitlabIntegrationRequest{
  ID: "",
  Host: "",
  Username: "",
  Token: "",
})
```
Where a user would not specify username or token for `GetGitlabIntegrationRequest` or `DeleteGitlabIntegrationRequest`

2021-01-13 12:41 UTC, josefkarasek commented on live/administration/v1alpha1/service.proto
> +    rpc CreateGitlabIntegration(CreateGitlabIntegrationRequest) returns (CreateGitlabIntegrationResponse) {
So something like this?
```
enum GitProvider {
    Github = 0;
    Gitlab = 1;
}

message GitIntegration {

    string id = 1;

    GitProvider provider = 2;

    GithubIntegration github = 3;

    GitlabIntegration gitlab = 4;
}

message GitlabIntegration {

    /*
    `Required`
    Gitlab server URL.
    */
    string host = 1;

    /*
    `Required`
    Username for the token.
    */
    string username = 2;

    /*
    `Required`
    Username for the token.
    */
    string token = 3;
}

message GithubIntegration {

    /*
    `Required`
    Github App ID.
    */
    int64 githubAppID = 1;

     /*
    `Optional`
    Github App Slug.
    */
    string githubAppSlug = 16;
}
```

2021-01-13 15:31 UTC, drekle approved these changes
lgtm.  I believe we can merge this to unblock work and determine if we can marry github and gitlab types in a future PR.

2021-01-13 15:31 UTC, drekle commented on live/administration/v1alpha1/service.proto
> +    rpc CreateGitlabIntegration(CreateGitlabIntegrationRequest) returns (CreateGitlabIntegrationResponse) {
```
message GitIntegration {

    string id = 1;

    GitProvider provider = 2;

    GithubIntegration github = 3;

    GitlabIntegration gitlab = 4;
}
```

I was kind of thinking something like
```
message GitIntegration {

    string id = 1;
    
    GitProvider type = 2;
    
    /*
    `Required`
    Git server URL.
    */
    string host = 3;

    /*
    `Required`
    Username for the token.
    */
    string username = 4;

    /*
    `Required`
    Access token for the user.
    */
    string token = 5;
}
```
As we can connect to both git providers in this way, however for a reason I must have forgotten we've decided to connect to github via the app.

Lets put this off for a future version however.

2021-01-14 14:49 UTC, merged